name: run-tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ 8.0, 7.4 ]
                dependency-version: [ prefer-lowest, prefer-stable ]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Install dependencies
                run: composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

            -   name: Run tests
                env:
                    API_TOKEN: ${{ secrets.API_TOKEN }}
                    MAIL_CHECKER_API_URL: ${{ secrets.MAIL_CHECKER_API_URL }}
                run: vendor/bin/phpunit
